'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const context={window:{crypto},crypto};
for(const name of ['ledger','customers','suppliers','payments','receipts','banking','bank-entries','reports'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../js/core',name+'.js'),'utf8'),context);
const {EvergreenBankEntries:entries,EvergreenBanking:bank,EvergreenPayments:payments,EvergreenReceipts:receipts,EvergreenLedger:ledger,EvergreenReports:reports}=context.window;
const blank=()=>({invoices:[],bills:[],expenses:[],payments:[],ledgerEntries:[],customers:[],suppliers:[],bankTransactions:[]});
const row=(id,amount,description='Bank test')=>({id,date:'2026-10-07',amount,description,status:'Unmatched'});
const financial=state=>JSON.stringify({invoices:state.invoices,expenses:state.expenses,payments:state.payments,ledger:state.ledgerEntries});
function balanced(state){const result=reports.trialBalance(state);assert.equal(result.totalDebit,result.totalCredit);}
const direct=blank();direct.bankTransactions.push(row('sale',120),row('expense',-60));
const sale=entries.createFromRow(direct,'sale',{party:'Customer',description:'New sale',reference:'INV-BANK-TEST',vatTreatment:'20'});
assert.equal(sale.document.status,'Paid');assert.equal(sale.document.totalNet,100);assert.equal(sale.document.totalVat,20);
assert.equal(direct.payments.length,1);assert.equal(direct.ledgerEntries.length,2);assert.equal(payments.outstandingAmount(direct,'Invoice',sale.document.id),0);
const expense=entries.createFromRow(direct,'expense',{party:'Supplier',description:'New expense',category:'Software & IT',vatTreatment:'20',attachment:'data:image/png;base64,TEST',fileName:'r.png',receipt:{fileName:'r.png'}});
assert.equal(expense.document.netAmount,50);assert.equal(expense.document.vatAmount,10);assert.equal(expense.document.grossAmount,60);
assert.equal(direct.expenses.length,1);assert.equal(direct.payments.length,1);assert.equal(direct.ledgerEntries.length,3);assert.equal(direct.bankTransactions.every(tx=>tx.status==='Matched'),true);balanced(direct);
const after=JSON.stringify(direct);assert.throws(()=>entries.createFromRow(direct,'sale',{party:'Customer',vatTreatment:'0'}));assert.equal(JSON.stringify(direct),after);
assert.throws(()=>receipts.revise(expense.document,{netAmount:55}));
assert.equal(receipts.revise(expense.document,{attachment:null}).grossAmount,60);
assert.equal(entries.documentLinked(direct,'Invoice',sale.document.id),true);assert.equal(entries.documentLinked(direct,'Expense',expense.document.id),true);
const partial=blank();const invoice={id:'INV-P',invNo:'INV-P',customer:'Existing Customer',type:'Invoice',date:'2026-10-07',totalNet:100,totalVat:20,totalGross:120,status:'Unpaid'};
partial.invoices.push(invoice);partial.ledgerEntries.push(ledger.fromDocument('Invoice',invoice));
const payment=payments.recordPayment(partial,{documentType:'Invoice',documentId:invoice.id,amount:40,date:'2026-10-07',reference:'INV-P'}).payment;
const originalFinancial=financial(partial);
bank.importRows(partial,[{date:'2026-10-07',description:'Existing Customer INV-P',amount:40}]);
const tx=partial.bankTransactions[0];assert.equal(tx.suggestedType,'Payment');assert.equal(bank.runAutoMatch(partial).matched,0);assert.equal(financial(partial),originalFinancial);
bank.acceptSuggestion(partial,tx.id);assert.equal(partial.payments.length,1);assert.equal(partial.ledgerEntries.length,2);assert.equal(payments.outstandingAmount(partial,'Invoice',invoice.id),80);balanced(partial);
partial.bankTransactions.push(row('second-payment',40));
const linked=JSON.stringify(partial);assert.throws(()=>entries.linkExisting(partial,'second-payment','Payment',payment.id));assert.equal(JSON.stringify(partial),linked);
const countBefore=partial.ledgerEntries.length;entries.unlinkExisting(partial,tx.id);assert.equal(partial.ledgerEntries.length,countBefore);assert.equal(payment.bankTransactionId,undefined);assert.equal(tx.status,'Unmatched');
assert.throws(()=>entries.createFromRow(partial,tx.id,{party:'Existing Customer',vatTreatment:'0'}));
entries.linkExisting(partial,tx.id,'Payment',payment.id);assert.equal(partial.payments.length,1);
const recorded=blank();const existingExpense=receipts.create({id:'EXISTING',merchant:'Merchant',date:'2026-10-07',netAmount:50,vatTreatment:'20',category:'Office Supplies',attachment:'data:image/png;base64,KEPT'});receipts.applyExpense(recorded,existingExpense,ledger);
recorded.bankTransactions.push(row('expense-link',-60),row('wrong-sign',60),row('wrong-amount',-61));
const oldJournal=JSON.stringify(recorded.ledgerEntries);entries.linkExisting(recorded,'expense-link','Expense',existingExpense.id);assert.equal(recorded.expenses.length,1);assert.equal(JSON.stringify(recorded.ledgerEntries),oldJournal);assert.equal(existingExpense.attachment,'data:image/png;base64,KEPT');
assert.throws(()=>entries.linkExisting(recorded,'wrong-sign','Expense',existingExpense.id));assert.throws(()=>entries.linkExisting(recorded,'wrong-amount','Expense',existingExpense.id));
entries.unlinkExisting(recorded,'expense-link');assert.equal(JSON.stringify(recorded.ledgerEntries),oldJournal);assert.equal(existingExpense.bankTransactionId,undefined);
const failed=blank();failed.bankTransactions.push(row('failure',-60));const original=JSON.stringify(failed);assert.throws(()=>entries.createFromRow(failed,'failure',{party:'Merchant',category:'Invalid',vatTreatment:'20'}));assert.equal(JSON.stringify(failed),original);
const legacy=blank();legacy.invoices.push({...invoice,status:'Part Paid'});legacy.payments.push({...payment,bankTransactionId:undefined});legacy.bankTransactions.push({...row('old',40,'INV-P'),status:'Matched',matchedType:'Invoice',matchedId:'INV-P'},row('new',40,'INV-P'));
assert.equal(entries.existingCandidates(legacy,'new').length,0);
const tiny=blank();tiny.bankTransactions.push(row('tiny',-0.03));const tinyExpense=entries.createFromRow(tiny,'tiny',{party:'Tiny',category:'Other Expenses',vatTreatment:'20'}).document;assert.equal(receipts.revise(tinyExpense,{notes:'Changed'}).grossAmount,0.03);balanced(tiny);
console.log('Bank entry creation and existing-record linking checks passed.');
