'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const context={window:{}};
for(const name of ['ledger','payments','banking'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../js/core',name+'.js'),'utf8'),context);
const api=context.window.EvergreenBanking,pay=context.window.EvergreenPayments;
const base=()=>({invoices:[{id:'INV-T1',invNo:'INV-T1',type:'Invoice',customer:'Test Customer',date:'2026-10-07',totalNet:100,totalVat:20,totalGross:120,status:'Unpaid'}],bills:[{id:'BIL-T1',billNo:'BIL-T1',type:'Bill',supplier:'Test Supplier',date:'2026-10-07',totalNet:50,totalVat:10,totalGross:60,status:'Unpaid'}],payments:[],ledgerEntries:[],bankTransactions:[]});
const csv='Date,Description,Amount\n07/10/2026,"Test Customer, INV-T1",120\n07/10/2026,Test Supplier BIL-T1,-60\n07/10/2026,Test Supplier BIL-T1,-60\n07/10/2026,Bank fee,-5';
const state=base(),imported=api.importRows(state,api.parseCsv(csv));
assert.equal(imported.imported,3);assert.equal(imported.duplicates,1);
assert.equal(api.runAutoMatch(state).matched,2);
assert.equal(state.payments.length,2);
for(const journal of state.ledgerEntries){const totals=context.window.EvergreenLedger.getTotals(journal);assert.equal(totals.debit,totals.credit);}
const summary=api.reconciliationSummary(state,1000);
assert.equal(summary.closingBalance,1055);assert.equal(summary.reconciledBalance,1060);assert.equal(summary.unmatchedMovement,-5);
assert.equal(api.importRows(state,api.parseCsv(csv)).imported,0);
const over=base();api.importRows(over,[{date:'2026-10-07',description:'Test Customer INV-T1',amount:120.01}]);
assert.equal(api.runAutoMatch(over).matched,0);
assert.throws(()=>api.matchTransaction(over,over.bankTransactions[0].id,'Invoice','INV-T1'));
assert.equal(over.payments.length,0);
const wrong=base();api.importRows(wrong,[{date:'2026-10-07',description:'Wrong direction',amount:-40}]);
assert.throws(()=>api.matchTransaction(wrong,wrong.bankTransactions[0].id,'Invoice','INV-T1'));assert.equal(wrong.payments.length,0);
const partial=base();api.importRows(partial,[{date:'2026-10-07',description:'Part payment',amount:40}]);
const id=partial.bankTransactions[0].id;api.matchTransaction(partial,id,'Invoice','INV-T1');
assert.throws(()=>api.matchTransaction(partial,id,'Invoice','INV-T1'));
assert.equal(partial.payments.length,1);assert.equal(pay.outstandingAmount(partial,'Invoice','INV-T1'),80);
const ambiguity=base();ambiguity.invoices.push({...ambiguity.invoices[0],id:'INV-T2',invNo:'INV-T2'});
api.importRows(ambiguity,[{date:'2026-10-07',description:'Test Customer INV-T1 INV-T2',amount:120}]);
assert.equal(api.runAutoMatch(ambiguity).matched,0);assert.equal(ambiguity.bankTransactions[0].status,'Suggested');
const multiline=api.parseCsv('Date,Description,Amount\n07/10/2026,"Test Customer,\nINV-T1",120');
assert.equal(multiline.length,1);assert.equal(multiline[0].amount,120);
assert.throws(()=>api.parseCsv('Date,Description,Amount\n31/02/2026,Invalid,10'));
assert.throws(()=>api.parseCsv('Date,Description,Amount\n07/10/2026,"unfinished,10'));
const separate=api.parseCsv('Date;Description;Debit;Credit\n07/10/2026;Test Customer INV-T1;;120\n07/10/2026;Test Supplier BIL-T1;60;');
assert.equal(separate[0].amount,120);assert.equal(separate[1].amount,-60);
console.log('Bank reconciliation regression checks passed.');
