'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const context={window:{crypto},crypto};
for(const name of ['ledger','receipts','customers','suppliers','payments','banking','bank-entries','reports','cash','state'])vm.runInNewContext(fs.readFileSync(__dirname+'/../js/core/'+name+'.js','utf8'),context);
const {EvergreenCash:c,EvergreenLedger:l,EvergreenReceipts:r,EvergreenReports:reports,EvergreenBankEntries:b,EvergreenPayments:p,EvergreenBanking:bank}=context.window;
const blank=()=>({expenses:[],invoices:[],bills:[],customers:[],suppliers:[],payments:[],ledgerEntries:[],bankTransactions:[]});
const state=blank();
const withdrawal=c.record(state,{type:'withdrawal',amount:200,date:'2026-10-01',reference:'ATM'});
r.applyExpense(state,r.create({merchant:'Shop',date:'2026-10-02',category:'Office Supplies',netAmount:145,vatTreatment:'20',payMethod:'Cash'}),l);
assert.equal(c.ledger(state).balance,26);assert.equal(c.ledger(state).inflows,200);assert.equal(c.ledger(state).outflows,174);
assert.equal(c.ledger(state,{from:'2026-10-02'}).opening,200);assert.equal(c.balanceAt(state,'2026-09-30'),0);
assert.equal(reports.profitAndLoss(state).totalExpenses,145);assert.equal(reports.balanceSheet(state).difference,0);
assert.equal(reports.cashFlow(state).netCashFlow,-174);
state.bankTransactions.push({id:'bank',date:'2026-10-01',amount:-200,description:'ATM',status:'Unmatched'});
const count=state.ledgerEntries.length;b.linkExisting(state,'bank','CashMovement',withdrawal.id);assert.equal(state.ledgerEntries.length,count);
assert.equal(reports.cashFlow(state).netCashFlow,-174);assert.throws(()=>c.reverse(state,withdrawal.id,'2026-10-03'));
b.unlinkExisting(state,'bank');bank.runAutoMatch(state);bank.acceptSuggestion(state,'bank');assert.equal(state.ledgerEntries.length,count);
b.unlinkExisting(state,'bank');const reversal=c.reverse(state,withdrawal.id,'2026-10-03');assert.equal(c.ledger(state).balance,-174);
assert.equal(b.existingCandidates(state,'bank').length,0);assert.throws(()=>c.reverse(state,withdrawal.id,'2026-10-03'));assert.throws(()=>c.reverse(state,reversal.id,'2026-10-03'));
const funded=blank();c.record(funded,{type:'opening',date:'2026-09-30',amount:50});
assert.throws(()=>c.record(funded,{type:'opening',date:'2026-10-01',amount:50}));
c.record(funded,{type:'capital',date:'2026-10-01',amount:100});c.record(funded,{type:'loan',date:'2026-10-01',amount:75});
assert.equal(c.ledger(funded).balance,225);assert.equal(reports.profitAndLoss(funded).netProfit,0);assert.equal(reports.balanceSheet(funded).difference,0);
assert.equal(reports.cashFlow(funded).inflows,175);
const snapshot=JSON.stringify(funded);assert.throws(()=>c.record(funded,{type:'deposit',date:'2026-10-02',amount:226}));assert.equal(JSON.stringify(funded),snapshot);
c.record(funded,{type:'deposit',date:'2026-10-02',amount:25});assert.equal(c.ledger(funded).balance,200);
for(const input of [{type:'opening',date:'bad',amount:1},{type:'loan',date:'2026-02-30',amount:1},{type:'unknown',date:'2026-10-01',amount:1},{type:'loan',date:'2026-10-01',amount:Infinity}])assert.throws(()=>c.record(blank(),input));
const invoice={id:'cash-sale',type:'Invoice',invNo:'CS1',customer:'Cash customer',date:'2026-10-03',totalNet:10,totalVat:2,totalGross:12,status:'Unpaid'};
funded.invoices.push(invoice);funded.ledgerEntries.push(l.fromDocument('Invoice',invoice));p.recordPayment(funded,{documentType:'Invoice',documentId:invoice.id,date:'2026-10-03',amount:12,method:'Cash'});
assert.equal(c.ledger(funded).balance,212);assert.equal(p.outstandingAmount(funded,'Invoice',invoice.id),0);
assert.equal(c.ledger(context.window.EvergreenState.normalize(JSON.parse(JSON.stringify(funded)))).balance,212);
const tb=reports.trialBalance(funded);assert.equal(tb.totalDebit,tb.totalCredit);
console.log('Cash funding, transfers, running balances, reversals, bank links, cash sales and restore normalization checks passed.');
