'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const context={window:{}};
for(const name of ['ledger','payments'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../js/core',name+'.js'),'utf8'),context);
const api=context.window.EvergreenPayments;
const invoice={id:'I1',invNo:'I1',type:'Invoice',totalNet:100,totalVat:20,totalGross:120,status:'Unpaid'};
const state={invoices:[invoice],bills:[],payments:[],ledgerEntries:[]};
assert.equal(api.paymentSummary(state,'Invoice','I1').status,'Unpaid');
api.recordPayment(state,{documentType:'Invoice',documentId:'I1',amount:40});
assert.equal(api.paymentSummary(state,'Invoice','I1').status,'Partially Paid');
assert.equal(api.paymentSummary(state,'Invoice','I1').outstanding,80);
api.recordPayment(state,{documentType:'Invoice',documentId:'I1',amount:80});
assert.equal(api.paymentSummary(state,'Invoice','I1').status,'Paid');
assert.equal(api.paymentSummary(state,'Invoice','I1').paid,120);
assert.equal(state.ledgerEntries.length,2);
assert.throws(()=>api.recordPayment(state,{documentType:'Invoice',documentId:'I1',amount:1}));
const legacy={invoices:[{...invoice,status:'Paid'}],bills:[],payments:[]};
assert.equal(api.paymentSummary(legacy,'Invoice','I1').outstanding,0);
assert.equal(api.paymentSummary(legacy,'Invoice','I1').paid,120);
console.log('Invoice payment-status regression checks passed.');
